In [2]:
import numpy as np

arr = np.array([1,2,3,4])
print(arr)

arr2 = np.array([[1,2,3,4],[1,2,3,4]])
print(arr2)

[1 2 3 4]
[[1 2 3 4]
 [1 2 3 4]]


In [4]:
import time

start = time.time()
list = [i*2 for i in range(900000)]
print(time.time()-start)

start = time.time()
arr = np.arange(900000) * 2
print(time.time()-start)

0.0641326904296875
0.0043544769287109375


In [17]:
zero = np.zeros((2,3))
print(zero)

one = np.ones((2,4))
print(one)

full = np.full((2,3),10)
print(full)

random  = np.random.random((2,3))
print(random)

seq = np.arange(10,20,2)
print(seq)

lin = np.linspace(10,20,5)
print(lin)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[10 10 10]
 [10 10 10]]
[[0.5922737  0.84192916 0.4560235 ]
 [0.98869799 0.82537745 0.25125737]]
[10 12 14 16 18]
[10.  12.5 15.  17.5 20. ]


In [20]:
vector = np.array([1,3,4,5])
print(vector)

matrix = np.array([[1,2],[3,4]])
print(matrix)

tensor = np.array([[[1,2,3],[1,3,4]],[[1,2,3],[1,2,3]]])
print(tensor)

[1 3 4 5]
[[1 2]
 [3 4]]
[[[1 2 3]
  [1 3 4]]

 [[1 2 3]
  [1 2 3]]]


In [24]:
# Properties
print(vector.shape)
print(matrix.size)
print(matrix.dtype)
print(tensor.ndim)

(4,)
4
int64
3


In [29]:
arr = np.array([1,2,3,4]).reshape(2,2)
print(arr)

print(arr.flatten())
print(arr.ravel())
print(arr.T)


[[1 2]
 [3 4]]
[1 2 3 4]
[1 2 3 4]
[[1 3]
 [2 4]]
