In [2]:
import numpy as np

Slicing in array

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

print(arr[3:6])
print(arr[2:8:2])
print(arr[-3:-1])


[ 1  2  3  4  5  6  7  8  9 10]
[4 5 6]
[3 5 7]
[8 9]


In [ ]:
arr2 = np.array([[1,2,3],
                 [4,5,6]])
print(arr2)

print(arr2[0,2])
print(arr2[0:1,0:2])
print(arr2[-1:-2,-2:-1])

print(arr[1])
print(arr[:1])

[[1 2 3]
 [4 5 6]]
3
[[1 2]]
[]
2
[1]


Sorting

In [ ]:
arr = np.array([1,-2,3,223,-23])
print(np.sort(arr))

arr2 = np.array([[1,2,3],[4,5,6],[1,6,4],[2,5,3]])
print("row wise",np.sort(arr2,axis=1))
print("column wise",np.sort(arr2,axis=0))


[-23  -2   1   3 223]
[[1 2 3]
 [4 5 6]
 [1 4 6]
 [2 3 5]]
[[1 2 3]
 [1 5 3]
 [2 5 4]
 [4 6 6]]


In [ ]:
print(arr2[arr2>3])

[4 5 6 6 4 5]


In [ ]:
print()
# filtering by mask

mask = arr2 > 3
print(arr2[mask])


[4 5 6 6 4 5]


In [ ]:
arr2 = np.array([1,2,3,4,5,6,7,8,9,10])
indices = [1,4,2]
print(arr2[indices])

[2 5 3]


In [ ]:
whe = np.where(arr2>5)
print(whe)
print(arr2[whe])

(array([5, 6, 7, 8, 9]),)
[ 6  7  8  9 10]


In [3]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.concatenate((arr1,arr2)))

[1 2 3 4 5 6]


In [8]:
arr = np.array([[1, 2],
                [3, 4]])

print("Original Array:")
print(arr)

arr1 = np.array([[5, 6]])

arr2 = np.array([[5, 6],
                 [7, 8]])

print("\nVertical Stack:")
print(np.vstack((arr, arr1)))

print("\nHorizontal Stack:")
print(np.hstack((arr, arr2)))

Original Array:
[[1 2]
 [3 4]]

Vertical Stack:
[[1 2]
 [3 4]
 [5 6]]

Horizontal Stack:
[[1 2 5 6]
 [3 4 7 8]]


In [11]:
print(arr)
array_deleted = np.delete(arr,1,axis=1)
print(array_deleted)

[[1 2]
 [3 4]]
[[1 2]]
